#!/bin/bash
wget https://cran.r-project.org/src/contrib/Archive/matrixStats/matrixStats_0.60.1.tar.gz
R CMD INSTALL matrixStats_0.60.1.tar.gz
wget https://bioconductor.org/packages/release/bioc/src/contrib/DESeq2_1.38.1.tar.gz
R CMD INSTALL DESeq2_1.38.1.tar.gz
curl https://storage.googleapis.com/demo-temp-files/key-file > ~/key-file
